### ISSUE TITLE
How to set the date of the calendar?

### ISSUE THREAD

**Issue by BSteephenson** [zfrenchee/Bluemoon#43]
@zfrenchee Can you put some comments in CalendarView::selectDay(day, date) explaining how to use it? What are day and date?

Need to know for populating the fields (the calendar is one of them) when editing an event.

**Comment by zfrenchee** [comment]
This will actually be reasonably difficult, because we'll need to make a real component out of the calendar, not just a wrapper for Calendario. You can actually hack around this if you fire a click event (from js) on the specific day, that'll do all the magic you want it to do. 

Otherwise, we can merge the PR without calendar populating, rework the calendar, and then add calendar population later. What do you think?

**Comment by BSteephenson** [comment]
Rewrote selectDay for CalendarView. See PR #44
